name: tap_caddie
description: A smart golf tracking app that uses NFC-tagged clubs and GPS to automatically log shots, track distances, and recommend clubs based on performance history.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_analytics: ^10.7.4

  # Authentication
  google_sign_in: ^6.1.6
  sign_in_with_apple: ^5.0.0

  # Location & Maps
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  location: ^5.0.3

  # NFC (will be simulated for now)
  nfc_manager: ^3.3.0

  # UI & Navigation
  go_router: ^12.1.3
  provider: ^6.1.1
  cupertino_icons: ^1.0.2

  # Utilities
  uuid: ^4.2.1
  intl: ^0.18.1
  shared_preferences: ^2.2.2

  # Charts for Analytics
  fl_chart: ^0.65.0

  # Image handling
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Uncomment these when you add real files to the corresponding folders
  # assets:
  #   - assets/images/
  #   - assets/icons/

  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700
